version: "3.10"

services:
  db:
    container_name: postgres-inove
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev@pg
      POSTGRES_DB: inove
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - inove

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_inove
    stdin_open: true
    tty: true
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - .env:/app/.env
    command: python manage.py runserver 0.0.0.0:8001
    depends_on:
      - db
    networks:
      - inove

volumes:
  pgdata:

networks:
  inove:
