# Generated by Django 4.2 on 2024-07-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='Nome')),
                ('catchPhrase', models.CharField(max_length=200, verbose_name='Slogan')),
                ('bs', models.CharField(max_length=200, verbose_name='BS')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=50, verbose_name='Latitude')),
                ('lng', models.CharField(max_length=50, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Geolocalização',
                'verbose_name_plural': 'Geolocalizações',
                'db_table': 'geo',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('suite', models.CharField(max_length=100, verbose_name='Complemento')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('zipcode', models.CharField(max_length=20, verbose_name='CEP')),
                ('geo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='information.geo')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'addresses',
            },
        ),
    ]
