# Generated by Django 4.2 on 2024-07-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=45, verbose_name='Telefone')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='information.address')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='information.company')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
        ),
    ]
